### ISSUE TITLE
links that don't resolve breaks sphinx

### ISSUE THREAD

**Issue by choldgraf** [ExecutableBookProject/MyST-Parser#89]
I came across a weird bug today:

Links that don't resolve properly seem to break Sphinx. Basically, any link that isn't either a correct target to a filename, or a URL, will result in this error:

```
Exception occurred:
  File "/home/choldgraf/anaconda/envs/dev/lib/python3.7/site-packages/sphinx/writers/html5.py", line 779, in unknown_visit
    raise NotImplementedError('Unknown node: ' + node.__class__.__name__)
NotImplementedError: Unknown node: TextElement
```

I reproduced this by adding any of these lines to the docs of myst_parser:

* `[test](test.html)`
* `[test](test.md)`
* `[test](install.md)` (page actually exists but wrong target name)
* `[test](blahblah)` (target doesn't exist)

but the error is *not* triggered with these links:

* `[test](install)`
* `[test](https://test.html)`

**Comment by chrisjsewell** [comment]
Ah, this would be partly this TODO: https://github.com/ExecutableBookProject/MyST-Parser/blob/cf3352c8a224af219cb062cfe467d7da9289284a/myst_parser/docutils_renderer.py#L304

Basically some code needs to written to (a) check the link is local (e.g. doesn't start with https, etc),
(b) get hold of the file extensions that sphinx deems 'linkable', then (c) if both these check pass, remove the extension. 

Thinking about it now though, maybe if these checks parse, then we should also actually check if the file exists and, if it does, then actually set it as equivalent to writing `` `doc{name.txt}` `` here: https://github.com/ExecutableBookProject/MyST-Parser/blob/cf3352c8a224af219cb062cfe467d7da9289284a/myst_parser/docutils_renderer.py#L583

Also, in relation to the actual exception, I think here: https://github.com/ExecutableBookProject/MyST-Parser/blob/cf3352c8a224af219cb062cfe467d7da9289284a/myst_parser/docutils_renderer.py#L593

I should have used a `literal` node, instead of a `TextElement` node.

See [`sphinx.roles.AnyXRefRole`](https://github.com/sphinx-doc/sphinx/blob/cd15ab658f76ce38c629fc9de31d35b2ba1061f1/sphinx/roles.py#L190) for how the ref roles actually work.

Maybe you want to do a PR 😁 ?

**Comment by choldgraf** [comment]
I might have time to give this a shot, though I am knee-deep in other projects right now that I was dropping during the 2 weeks I didn't work on anything but the EBP lol. I'll try to make time for it if I can! It'll be one of those "if I can fix it in 15 minutes I'll do it, but if it's an unknown amount of time I won't have time" kinda things...

**Comment by chrisjsewell** [comment]
Same lol. Well I've also labelled it as 'good first issue' in case any of @jstac / @mmcky's guys want to give it a go.

If someone does do it; make sure you write some tests! (3 and 4 from here https://myst-parser.readthedocs.io/en/latest/develop/test_infrastructure.html#testing-infrastructure)
